@startuml
!define C4Context
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!include ../graphic-charter/c4_style.iuml

title Opti-Factory - C4 System Context Diagram

' OptiFactory system as the core
System(optifactory, "Opti-Factory", "Python program to optimize production lines for the game Satisfactory")

' External entities
Person(user, "User", "Player of Satisfactory")
System_Ext(satisfactoryGame, "Satisfactory Game", "The source of production data")
System_Ext(plantUML, "PlantUML", "Generates visual representation of production lines")

' Relationships
Rel(user, optifactory, "Inputs production plans and receives optimized production lines")
Rel(optifactory, satisfactoryGame, "Uses production data from")
Rel(optifactory, plantUML, "Uses to generate visual representation of production lines")

SHOW_LEGEND()

@enduml
